services:
  postgres:
    image: postgres:18-alpine
    container_name: nac_postgres
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nac_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: nac_redis
    networks:
      - nac_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: nac_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - nac_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./api:/app

  freeradius:
      build: ./freeradius
      command: -X
      ports:
        - "1812:1812/udp"
        - "1813:1813/udp"
      networks:
        - nac_network
      depends_on:
        - api
        - postgres
      restart: always
      

networks:
  nac_network:
    driver: bridge

volumes:
  pgdata: